// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('llamaApp').controller('AdventureCtrl', function($scope, $interval) {
    $scope.questionOneCorrect = void 0;
    $scope.questionTwoCorrect = void 0;
    $scope.questionThreeCorrect = void 0;
    $scope.questionFourCorrect = void 0;
    $scope.pageOneCountdownSet = function() {
      $interval(function() {
        return $scope.showLine = $scope.showLine + 1;
      }, 2000);
    };
    $scope.pageTwoCountdownSet = function() {
      $interval(function() {
        return $scope.showLineTwo = $scope.showLineTwo + 1;
      }, 2000);
    };
    $scope.pageTwoNegCountdownSet = function() {
      $interval(function() {
        return $scope.showLineTwoNeg = $scope.showLineTwoNeg + 1;
      }, 2000);
    };
    $scope.pageThreeCountdownSet = function() {
      $interval(function() {
        return $scope.showLineThree = $scope.showLineThree + 1;
      }, 2000);
    };
    return $scope.checkAnswers = function() {
      $scope.totalCorrect = 0;
      $scope.questionOneAnswerCheck = $scope.questionOneAnswer.toLowerCase();
      $scope.questionTwoAnswerCheck = $scope.questionTwoAnswer.toLowerCase();
      $scope.questionThreeAnswerCheck = $scope.questionThreeAnswer.toLowerCase();
      $scope.questionFourAnswerCheck = $scope.questionFourAnswer.toLowerCase();
      if ($scope.questionOneAnswerCheck === 'y' || $scope.questionOneAnswerCheck === 'yes') {
        $scope.questionOneCorrect = true;
        $scope.totalCorrect = $scope.totalCorrect + 1;
      } else {
        $scope.questionOneCorrect = false;
      }
      if ($scope.questionTwoAnswerCheck === 'y' || $scope.questionTwoAnswerCheck === 'yes') {
        $scope.questionTwoCorrect = true;
        $scope.totalCorrect = $scope.totalCorrect + 1;
      } else {
        $scope.questionTwoCorrect = false;
      }
      if ($scope.questionThreeAnswerCheck === 'y' || $scope.questionThreeAnswerCheck === 'yes') {
        $scope.questionThreeCorrect = true;
        $scope.totalCorrect = $scope.totalCorrect + 1;
      } else {
        $scope.questionThreeCorrect = false;
      }
      if ($scope.questionFourAnswerCheck === 'y' || $scope.questionFourAnswerCheck === 'yes') {
        $scope.questionFourCorrect = true;
        return $scope.totalCorrect = $scope.totalCorrect + 1;
      } else {
        return $scope.questionFourCorrect = false;
      }
    };
  });

}).call(this);
