// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('llamaApp').controller('AdventureCtrl', function($scope, $interval) {
    $scope.awesomeThings = [];
    $scope.test = 'TEEEEEST';
    console.log($scope.username);
    console.log($scope.pageOneCountdown);
    if ($scope.pageOneCountdown === true) {
      console.log('TRUE');
      $scope.pageOneLines = $interval(function() {
        console.log('EY');
        $scope.showLine = $scope.showLine + 1;
      }, 3000);
    }
  });

}).call(this);
