// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("llamaApp").controller("MainCtrl", function($scope) {
    $scope.awesomeThings = [];
    console.log('YOYO');
  });

}).call(this);
