// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('llamaApp').controller('StudyCtrl', function($scope) {
    $scope.awesomeThings = [];
    $scope.test = 'STUDYYUDTUYDU';
  });

}).call(this);
